spring:
  profiles:
    active: dev
  flyway:
	enabled: true
		default-schema: entity
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
shared:
  openapi:
    title: Catalog Service
    description: Feature catalog APIs
  core:
    correlation:
      header-name: X-Correlation-Id
      generate-if-missing: true
      echo-response-header: true
    tenant:
      enabled: true
      header-name: x_tenant_id
      query-param: tenantId
      default-policy: OPTIONAL
      echo-response-header: true
