spring:
  config:
    import: optional:classpath:application-shared-platform-dev.yaml
  datasource:
    url: "${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lms}?currentSchema=catalog}"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-ejada
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000        # 30s
      connection-timeout: 300000 # 300s
      max-lifetime: 1800000      # 30m

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: catalog
        hbm2ddl.create_namespaces: true
        format_sql: false
        jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
    schemas: public,catalog
    default-schema: catalog

  kafka:
    client-id: ejada-catalog-dev
shared:
  openapi:
    enabled: true
    title: " catalog Service API"
    description: "catalog service endpoints for tenant/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: catalog
      packages-to-scan:
        - com.ejada.catalog
    jwt-security: false

app:
  schema: catalog
  cache-prefix: catalog
  tenant-provisioning:
    topic: tenant.provisioning
    consumer-group: catalog-tenant-provisioning
