spring:
  application:
    name: catalog-service
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/lms
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: catalog
    schemas: catalog
    url: jdbc:postgresql://postgres:5432/lms
    user: postgres
    password: postgres
  webflux:
    base-path: /catalog

server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/plain
      - text/css
      - application/json
      - application/javascript
    min-response-size: 2KB
  error:
    include-message: always
    include-binding-errors: always

shared:
  observability:
    application-name: catalog-service
  security:
    enable-role-check: true
    jwt:
      token-period: 15m