spring:
  config:
    import: optional:classpath:application-shared-platform-dev.yaml

shared:
  openapi:
    enabled: true
    title: " catalog Service API"
    description: "catalog service endpoints for tenant/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: catalog
      packages-to-scan:
        - com.ejada.catalog
    jwt-security: false

app:
  kafka:
    client-id: ejada-catalog-dev
  jpa:
    show-sql: true
    format-sql: false
  tenant-provisioning:
    topic: tenant.provisioning
    consumer-group: catalog-tenant-provisioning
