spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/postgres
    username: postgres
    password: postgres
  flyway:
    locations: classpath:db/migration
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
shared:
  openapi:
    title: Catalog Service
    description: Feature catalog APIs
