spring:
  application:
    name: catalog-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: catalog
    schemas: catalog

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /catalog
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/plain
      - text/css
      - application/json
      - application/javascript
    min-response-size: 2KB
  error:
    include-message: always
    include-binding-errors: always

shared:
  observability:
    application-name: catalog-service
  security:
    enable-role-check: true
    jwt:
      token-period: 15m