spring:
  application:
    name: catalog-service
  main:
    lazy-initialization: ${SPRING_MAIN_LAZY_INITIALIZATION:true}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    default-schema: ${app.schema}
    schemas: ${app.schema}

app:
  schema: catalog
  cache-prefix: catalog

server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /catalog
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/plain
      - text/css
      - application/json
      - application/javascript
    min-response-size: 2KB
  error:
    include-message: always
    include-binding-errors: always

shared:
  observability:
    application-name: catalog-service
  security:
    enable-role-check: true
    resource-server:
      enabled: true
      verify-tenant-claim: true
    tenant-verification:
      strict-mode: true
      require-tenant-header: true
    jwt:
      token-period: 15m
