spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lms
    username: postgres
    password: postgres
  redis:
    host: 127.0.0.1
    port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  flyway:
    enabled: true
    default-schema: entity
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
server:
  port: 8080
shared:
  core:
    correlation:
      header-name: X-Correlation-Id
      generate-if-missing: true
      echo-response-header: true
    tenant:
      enabled: true
      header-name: x_tenant_id
      query-param: tenantId
      default-policy: OPTIONAL
      echo-response-header: true
  openapi:
    title: Catalog Service
    description: Feature catalog APIs
