spring:
  config:
    import:
      - optional:classpath:application-shared-platform-dev.yaml

app:
  kafka:
    client-id: ejada-setup-dev
  jpa:
    show-sql: true

shared:
  openapi:
    enabled: true
    title: " Setup Service API"
    description: "Setup service endpoints for tenant/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: setup
      packages-to-scan:
        - com.ejada.setup
    jwt-security: false
  security:
    mode: hs256
    jwt:
      secret: ${JWT_SECRET:7h1aH9UllV2E7Yka4P6s2F+1Vn6V5w9zIXhmJ5aB1kA=}
      token-period: 15m
    hs256:
      secret: ${JWT_SECRET:7h1aH9UllV2E7Yka4P6s2F+1Vn6V5w9zIXhmJ5aB1kA=}
    resource-server:
      enabled: true
      verify-tenant-claim: true
      permit-all:
        - "/**"
      disable-csrf: false
    tenant-verification:
      strict-mode: true
      require-tenant-header: true
    stateless: true
    roles-claim: roles
    tenant-claim: tenant
    enable-role-check: false
  crypto:
    algorithm: AES_GCM
    in-memory:
      activeKid: ${CRYPTO_ACTIVE_KID:local-dev-key}
      keys:
        local-dev-key: ${CRYPTO_LOCAL_DEV_KEY:4J8bfqUaEqzJCQakoJPM3w==}
