apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-api-gateway
spec:
  replicas: 6
  template:
    metadata:
      annotations:
        traffic.canary.weighing/primary: "90"
        traffic.canary.weighing/canary: "10"
    spec:
      containers:
        - name: api-gateway
          resources:
            limits:
              cpu: "1500m"
              memory: 3Gi
            requests:
              cpu: "750m"
              memory: 1.5Gi
