version: "3.8"

# ----------------------------- #
#          Reusable bits        #
# ----------------------------- #
x-health-defaults: &health_defaults
  interval: 10s
  timeout: 5s
  retries: 10
  start_period: 15s

x-restart: &restart_policy
  restart: unless-stopped

x-resources-light: &resources_light
  deploy:
    resources:
      limits:
        memory: 1g
      reservations:
        memory: 256m

# --- Common environment anchors ---
x-postgres-env: &postgres_env
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/lms
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres

x-redis-env: &redis_env
  SPRING_DATA_REDIS_HOST: redis
  SPRING_DATA_REDIS_PORT: 6379

x-otel-env: &otel_env
  OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  OTEL_TRACES_EXPORTER: otlp
  OTEL_METRICS_EXPORTER: otlp

# ----------------------------- #
#       Networks & Volumes      #
# ----------------------------- #
networks:
  backend:
    driver: bridge

volumes:
  pgdata:
  zkdata:
  zklog:
  kafkadata:

# ----------------------------- #
#            Services           #
# ----------------------------- #
services:

  postgres:
    image: postgres:16
    <<: [*restart_policy, *resources_light]
    environment:
      POSTGRES_DB: lms
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Riyadh
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "pg_isready -U postgres -d lms"]
    networks:
      backend:
        aliases: [postgres]

  redis:
    image: redis:7
    <<: [*restart_policy, *resources_light]
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "redis-cli -h localhost ping | grep -q PONG"]
    networks:
      backend:
        aliases: [redis]

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    <<: [*restart_policy, *resources_light]
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 3000
      ZOOKEEPER_SYNC_LIMIT: 2
    ports:
      - "2181:2181"
    volumes:
      - zkdata:/var/lib/zookeeper/data
      - zklog:/var/lib/zookeeper/log
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "echo srvr | nc -w 2 localhost 2181 | grep -q 'Mode:'"]
    networks:
      backend:
        aliases: [zookeeper]

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    <<: [*restart_policy, *resources_light]
    depends_on:
      zookeeper:
        condition: service_healthy
    environment:
      TZ: Asia/Riyadh
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 168
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
      KAFKA_MESSAGE_MAX_BYTES: 20971520
      KAFKA_REPLICA_FETCH_MAX_BYTES: 20971520
      KAFKA_HEAP_OPTS: "-Xms512m -Xmx1024m"
    ports:
      - "9092:9092"
      - "29092:29092"
    volumes:
      - kafkadata:/var/lib/kafka/data
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list >/dev/null 2>&1"]
    networks:
      backend:
        aliases: [kafka]

  otel-collector:
    image: otel/opentelemetry-collector:latest
    <<: [*restart_policy, *resources_light]
    volumes:
      - "./shared-lib/shared-starters/starter-observability/src/main/resources:/etc/otelcol:ro"
    command: ["--config=/etc/otelcol/otel-collector-config.yaml"]
    ports:
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    healthcheck:
      <<: *health_defaults
      test: ["CMD", "/otelcol", "--version"]
    networks:
      backend:
        aliases: [otel-collector]

  # ----------------------------- #
  #       Application stack       #
  # ----------------------------- #

  tenant-service:
    build:
      context: ./tenant-platform/tenant-service
      dockerfile: Dockerfile
    <<: [*restart_policy]
    depends_on:
      postgres: { condition: service_healthy }
      otel-collector: { condition: service_started }
    environment:
      TZ: Asia/Riyadh
      <<: [*postgres_env, *redis_env, *otel_env]
      OTEL_SERVICE_NAME: tenant-service
    ports:
      - "8080:8080"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/core/actuator/health || exit 1"]
    networks:
      backend:

  setup-service:
    build:
      context: ./setup-service
      dockerfile: Dockerfile
    <<: [*restart_policy]
    depends_on:
      postgres: { condition: service_healthy }
      otel-collector: { condition: service_started }
    environment:
      TZ: Asia/Riyadh
      <<: [*postgres_env, *redis_env, *otel_env]
      OTEL_SERVICE_NAME: setup-service
    ports:
      - "8081:8080"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/core/actuator/health || exit 1"]
    networks:
      backend:

  billing-service:
    build:
      context: ./tenant-platform/billing-service
      dockerfile: Dockerfile
    <<: [*restart_policy]
    depends_on:
      postgres: { condition: service_healthy }
      otel-collector: { condition: service_started }
    environment:
      TZ: Asia/Riyadh
      <<: [*postgres_env, *redis_env, *otel_env]
      OTEL_SERVICE_NAME: billing-service
    ports:
      - "8082:8080"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/core/actuator/health || exit 1"]
    networks:
      backend:

  catalog-service:
    build:
      context: ./tenant-platform/catalog-service
      dockerfile: Dockerfile
    <<: [*restart_policy]
    depends_on:
      postgres: { condition: service_healthy }
      otel-collector: { condition: service_started }
    environment:
      TZ: Asia/Riyadh
      <<: [*postgres_env, *redis_env, *otel_env]
      OTEL_SERVICE_NAME: catalog-service
    ports:
      - "8083:8080"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/core/actuator/health || exit 1"]
    networks:
      backend:

  subscription-service:
    build:
      context: ./tenant-platform/subscription-service
      dockerfile: Dockerfile
    <<: [*restart_policy]
    depends_on:
      postgres: { condition: service_healthy }
      otel-collector: { condition: service_started }
    environment:
      TZ: Asia/Riyadh
      <<: [*postgres_env, *redis_env, *otel_env]
      OTEL_SERVICE_NAME: subscription-service
    ports:
      - "8084:8080"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/core/actuator/health || exit 1"]
    networks:
      backend:

  security-service:
    build:
      context: ./sec-service
      dockerfile: Dockerfile
    <<: [*restart_policy]
    depends_on:
      postgres: { condition: service_healthy }
      redis:    { condition: service_healthy }
      otel-collector: { condition: service_started }
    environment:
      TZ: Asia/Riyadh
      <<: [*postgres_env, *redis_env, *otel_env]

      # Extra Redis settings (security-specific)
      SHARED_REDIS_HOST: redis
      SHARED_REDIS_PORT: 6379
      SHARED_REDIS_TIMEOUT: 5s
      SHARED_REDIS_KEY_PREFIX: security
      SHARED_REDIS_DEFAULT_TTL: 600s

      OTEL_SERVICE_NAME: security-service
    ports:
      - "8085:8080"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/core/actuator/health || exit 1"]
    networks:
      backend:

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    <<: [*restart_policy]
    depends_on:
      setup-service: { condition: service_started }
      tenant-service: { condition: service_started }
      catalog-service: { condition: service_started }
      subscription-service: { condition: service_started }
      billing-service: { condition: service_started }
      security-service: { condition: service_started }
      redis: { condition: service_healthy }
      otel-collector: { condition: service_started }
    environment:
      TZ: Asia/Riyadh
      <<: [*redis_env, *otel_env]
      OTEL_SERVICE_NAME: api-gateway
      SHARED_SECURITY_MODE: hs256
      SHARED_SECURITY_HS256_SECRET: ${JWT_SECRET:-local-dev-secret}
      SHARED_SECURITY_RESOURCE_SERVER_ENABLED: "false"
      SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_SETUP_SERVICE_0_URI: http://setup-service:8080
      SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_TENANT_SERVICE_0_URI: http://tenant-service:8080
      SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_CATALOG_SERVICE_0_URI: http://catalog-service:8080
      SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_SUBSCRIPTION_SERVICE_0_URI: http://subscription-service:8080
      SPRING_CLOUD_DISCOVERY_CLIENT_SIMPLE_INSTANCES_BILLING_SERVICE_0_URI: http://billing-service:8080
    ports:
      - "8088:8080"
    healthcheck:
      <<: *health_defaults
      test: ["CMD-SHELL", "wget --spider --quiet http://localhost:8080/actuator/health || exit 1"]
    networks:
      backend:
