spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  autoconfigure:
    exclude:
      - com.ejada.shared_starter_ratelimit.RateLimitAutoConfiguration
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      httpclient:
        connect-timeout: 5000
        response-timeout: 10s
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://otel-collector:4317

# Disable servlet security auto configuration (we provide reactive equivalent)
shared:
  security:
    resource-server:
      enabled: false

  core:
    tenant:
      enabled: true
    correlation:
      enabled: true

  observability:
    application-name: ${spring.application.name}

  ratelimit:
    enabled: false

# Declarative downstream routes consumed by GatewayRoutesConfiguration
gateway:
  routes:
    setup:
      id: setup-service
      uri: lb://setup-service
      paths:
        - /api/setup/**
      strip-prefix: 1
      resilience:
        enabled: true
        fallback-uri: forward:/fallback/setup-service
    tenant:
      id: tenant-service
      uri: lb://tenant-service
      paths:
        - /api/tenant/**
      strip-prefix: 1
      resilience:
        enabled: true
        fallback-uri: forward:/fallback/tenant-service
    catalog:
      id: catalog-service
      uri: lb://catalog-service
      paths:
        - /api/catalog/**
      strip-prefix: 1
      resilience:
        enabled: true
        fallback-uri: forward:/fallback/catalog-service
    subscription:
      id: subscription-service
      uri: lb://subscription-service
      paths:
        - /api/subscription/**
      strip-prefix: 1
      resilience:
        enabled: true
        fallback-uri: forward:/fallback/subscription-service
    billing:
      id: billing-service
      uri: lb://billing-service
      paths:
        - /api/billing/**
      strip-prefix: 1
      resilience:
        enabled: true
        fallback-uri: forward:/fallback/billing-service

logging:
  level:
    root: INFO
    com.ejada.gateway: DEBUG
