spring:
  cloud:
    gateway:
      default-filters: &gateway-default-filters
        - name: RequestSize
          args:
            maxSize: 10MB
        - name: SaveSession
      x-forwarded:
        enabled: true
        for-enabled: true
        proto-enabled: true
        host-enabled: true
        port-enabled: true
      metrics:
        enabled: true
        tags:
          - tenantId
          - routeId
      httpclient:
        connect-timeout: 5000
        response-timeout: 15s
        pool:
          name: gateway-pool
          type: elastic
          max-idle-time: 60s
          evict-in-background: 30s
      redis-rate-limiter:
        include-headers: true
      discovery:
        locator:
          enabled: false
      routes: []
    loadbalancer:
      client:
        name: ${SPRING_CLOUD_LOADBALANCER_CLIENT_NAME:${spring.application.name}}
      retry:
        enabled: true
      sticky-session:
        enabled: true
        add-service-instance-cookie: true
        cookie-name: LMS-AFFINITY
    kubernetes:
      enabled: ${SPRING_CLOUD_KUBERNETES_ENABLED:false}
      discovery:
        enabled: ${SPRING_CLOUD_KUBERNETES_DISCOVERY_ENABLED:${spring.cloud.kubernetes.enabled}}
        all-namespaces: false
        include-not-ready-addresses: false
        wait-cache-ready: true
        cache-loading-timeout-seconds: 30
        namespaces:
          - ${SPRING_CLOUD_KUBERNETES_DISCOVERY_NAMESPACE:${KUBERNETES_NAMESPACE:}}
        metadata:
          add-pod-labels: true
          add-pod-annotations: true
      loadbalancer:
        enabled: ${SPRING_CLOUD_KUBERNETES_LOADBALANCER_ENABLED:${spring.cloud.kubernetes.enabled}}
        mode: POD
      reload:
        enabled: true
        mode: event
        monitoring-config-maps: true
        monitoring-secrets: true

gateway:
  internal:
    api-key: ${GATEWAY_INTERNAL_API_KEY:${SHARED_SECURITY_INTERNAL_CLIENT_API_KEY:local-dev-internal-key}}
  tracing:
    enhanced-tags:
      enabled: true
  bff:
    dashboard:
      tenant-service-uri: lb://tenant-service
  security:
    signature-validation:
      enabled: false
      skip-patterns:
        - /public/**
        - ${shared.patterns.actuator.generic}
        - ${shared.patterns.auth.auth-root}
    api-key:
      enabled: true
      encryption:
        enabled: true
        algorithm: AES-256-GCM
        key-id: default
        key-value: ${GATEWAY_API_KEY_ENCRYPTION_KEY:}
      rotation:
        enabled: true
        max-age-days: 90
      scope-enforcement:
        enabled: true
        require-exact-match: false
      audit:
        log-usage: true
        track-last-used: true
    token-cache:
      enabled: false
      ttl: 15m
    ip-filtering:
      enabled: false
      analytics-service-uri: lb://analytics-service
      billing-service-uri: lb://billing-service
      default-period: MONTHLY
  defaults:
    max-request-size: 10MB
    routes:
      tenant-service: &defaults-tenant-route
        uri: lb://tenant-service
        paths:
          - /api/v1/tenants/**
          - /api/tenants/**
          - /api/tenant/**
        strip-prefix: 0
        prefix-path: /tenant
        versioning: &defaults-tenant-versioning
          enabled: true
          default-version: v1
          supported-versions:
            - v1
        session-affinity:
          enabled: true
          cookie-name: LMS-TENANT-AFFINITY
          header-name: X-Tenant-Affinity
    resilience:
      enabled: true
      fallback-uri: forward:/fallback/default
      fallback-status: SERVICE_UNAVAILABLE
      priority: NON_CRITICAL
      retry:
        enabled: true
        retries: 2
        methods:
          - GET
        statuses:
          - BAD_GATEWAY
          - SERVICE_UNAVAILABLE
        backoff:
          enabled: true
          first-backoff: 100ms
          max-backoff: 2s
          factor: 2
          based-on-previous-value: true
  logging:
    access-log:
      enabled: true
      skip-patterns:
        - ${shared.patterns.actuator.generic}
        - /health
  cache:
    enabled: true
    warm-interval: 10m
    warm-on-startup: false
    warm-tenants:
      - demo
    topics:
      tenant-updated: tenant.updated
      catalog-plan-updated: catalog.plan.updated
      subscription-changed: subscription.changed
    kafka:
      group-id: gateway-cache
    smart:
      patterns:
        - name: catalog
          path: /api/v1/catalog/**
          ttl: 5m
        - name: tenant
          path: /api/v1/tenants/**
          ttl: 1m
    routes:
      - &cache-client-base
        id: catalog-plans
        route-id: catalog-service
        method: GET
        path: /api/v1/catalog/plans
        ttl: 0s
        warm: true
        tenant-scoped: true
        client: &cache-client-config
          authorization: ${GATEWAY_CACHE_CATALOG_AUTHORIZATION:}
          api-key: ${GATEWAY_CACHE_CATALOG_API_KEY:}
          timeout: ${GATEWAY_CACHE_CLIENT_TIMEOUT:10s}
          headers:
            X-Internal-Request: "true"
      - <<: *cache-client-base
        id: catalog-features
        path: /api/v1/catalog/features
      - id: tenant-by-id
        route-id: tenant-service
        method: GET
        path: /api/v1/tenants/{id}
        ttl: 0s
        warm: false
        tenant-scoped: true
  subscription:
    enabled: true
    validation-uri: lb://subscription-service/internal/subscriptions/{tenantId}
    cache-ttl: 5m
    cache-prefix: "gateway:subscription:"
    fail-open: true
    validate-all-routes: true
    skip-patterns:
      - ${shared.patterns.actuator.generic}
      - ${shared.patterns.misc.fallback}
      - ${shared.patterns.auth.auth-root}
      - ${shared.patterns.misc.auth-root-sec}
      - ${shared.patterns.auth.api-auth}
      - ${shared.patterns.auth.api-auth-v1}
      - ${shared.patterns.auth.api-auth-sec}
      - ${shared.patterns.docs.api-swagger-single}
      - ${shared.patterns.docs.api-swagger-double}
      - ${shared.patterns.docs.api-v3-single}
      - ${shared.patterns.docs.api-v3-double}
      - ${shared.patterns.docs.root-swagger}
      - ${shared.patterns.docs.root-v3}
    required-features:
      catalog-service: catalog.read
      billing-service: billing.manage
      subscription-service: subscription.manage
    warmup:
      enabled: true
      tenant-service-uri: lb://tenant-service/api/v1/tenants
      refresh-interval: PT2M
      page-size: 200
      policy-service: policy.manage
  webclient:
    connect-timeout: 3s
    response-timeout: 15s
    read-timeout: 10s
    write-timeout: 10s
    max-in-memory-size: 5242880
  admin:
    aggregation:
      timeout: 3s
      services:
        - id: tenant-service
          uri: lb://tenant-service
          health-path: /actuator/health
          required: true
          deployment: primary
        - id: tenant-service-canary
          uri: lb://tenant-service
          health-path: /actuator/health
          required: false
          deployment: canary
          headers:
            X-Gateway-Track: canary
        - id: catalog-service
          uri: lb://catalog-service
          health-path: /actuator/health
          required: true
          deployment: primary
        - id: subscription-service
          uri: lb://subscription-service
          health-path: /actuator/health
          required: true
          deployment: primary
        - id: billing-service
          uri: lb://billing-service
          health-path: /actuator/health
          required: true
          deployment: primary
        - id: setup-service
          uri: lb://setup-service
          health-path: /actuator/health
          required: true
          deployment: primary
        - id: security-service
          uri: lb://security-service
          health-path: /actuator/health
          required: true
          deployment: primary
        - id: policy-service
          uri: lb://policy-service
          health-path: /actuator/health
          required: false
          deployment: primary
