logging:
  level:
    root: INFO
    com.ejada.gateway: INFO
  pattern:
    level: "%5p [${spring.application.name},trace=%X{traceId:-},span=%X{spanId:-},tenant=%X{tenantId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops,gateway,refresh
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    metrics:
      enabled: true
    gateway:
      enabled: true
  health:
    circuitbreakers:
      enabled: false
    discovery:
      enabled: false
    loadbalancer:
      enabled: false
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://otel-collector:4317}
  metrics:
    tags:
      application: ${spring.application.name}
      region: ${GCP_REGION:unknown}

reactor:
  context-propagation: auto
  netty:
    ioWorkerCount: ${REACTOR_NETTY_IO_WORKERS:0}
