spring:
  config:
    import: optional:classpath:application-shared-service.yaml

app:
  environment: qa
  service-code: tenant
  cache-prefix: ejada
  kafka:
    client-id: ${app.kafka-client-id:ejada-${app.service-code}-${app.environment}}
  jpa:
    show-sql: true

shared:
  core:
    correlation:
      header-name: X-Correlation-Id
      generate-if-missing: true
      echo-response-header: true
    tenant:
      enabled: true
      header-name: X-Tenant-Id
      query-param: tenantId
      default-policy: OPTIONAL
      echo-response-header: true
    cors:
      enabled: true
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
  headers:
    enabled: true
    correlation:
      header: X-Correlation-Id
      auto-generate: true
      mandatory: true
    request:
      header: X-Request-ID
      auto-generate: true
      mandatory: true
    tenant:
      header: X-Tenant-Id
      auto-generate: false
      mandatory: false
    user:
      header: X-User-Id
      auto-generate: false
      mandatory: false
    mdc:
      enabled: true
    security:
      enabled: true
      hsts:
        enabled: true
        max-age: 31536000
        include-subdomains: true
      frame-options: SAMEORIGIN
      content-type-options: nosniff
      referrer-policy: no-referrer
      xss-protection: "1; mode=block"
    propagation:
      enabled: true
      include:
        - X-Correlation-Id
        - X-Request-ID
        - X-Tenant-Id
        - X-User-Id
  audit:
    enabled: true
    web:
      enabled: true
      include-headers: true
      track-bodies: true
    aop:
      enabled: true
    dispatcher:
      async: true
    retention:
      enabled: true
      days: 90
    masking:
      enabled: true
      fields-by-key:
        - password
        - secret
        - token
        - ssn
    sinks:
      db:
        enabled: true
        schema: ${app.schema}
        table: audit_logs
      kafka:
        enabled: true
        topic: audit_logs
      otlp:
        enabled: false
      outbox:
        enabled: false
  redis:
    host: ${REDIS_HOST:redis}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:2s}
    key-prefix: ejada
    default-ttl: ${REDIS_DEFAULT_TTL:600s}
    reactive: false
  crypto:
    algorithm: AES_GCM
    in-memory:
      activeKid: ${CRYPTO_ACTIVE_KID:local-qa-key}
      keys:
        local-qa-key: ${CRYPTO_LOCAL_QA_KEY}
  security:
    mode: hs256
    jwt:
      secret: ${JWT_SECRET}
      token-period: 15m
    hs256:
      secret: ${JWT_SECRET}
    resource-server:
      enabled: true
      permit-all:
        - "**"
      disable-csrf: false
    stateless: true
    roles-claim: roles
    tenant-claim: tenant
    enable-role-check: true
