spring:
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      properties:
        max.poll.interval.ms: 300000
        max.poll.records: 500
    producer:
      acks: all
      retries: 3
      batch-size: 16384
      compression-type: gzip
      properties:
        linger.ms: 5
  data:
    redis:
      repositories:
        enabled: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,beans,conditions,configprops,loggers,threaddump
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    display-request-duration: true
    filter: true
    operationsSorter: method
    tagsSorter: alpha

shared:
  core:
    correlation:
      header-name: X-Correlation-Id
      generate-if-missing: true
      echo-response-header: true
    cors:
      enabled: true
      allowed-origins: ${GATEWAY_ALLOWED_ORIGINS:http://localhost:3000}
      allowed-methods: ${GATEWAY_ALLOWED_METHODS:GET,POST,PUT,DELETE,OPTIONS}
      allowed-headers: ${GATEWAY_ALLOWED_HEADERS:*}
  headers:
    enabled: true
    correlation:
      header: X-Correlation-Id
      auto-generate: true
      mandatory: true
    request:
      header: X-Request-ID
      auto-generate: true
      mandatory: true
    user:
      header: X-User-Id
      auto-generate: false
      mandatory: false
    mdc:
      enabled: true
    security:
      enabled: true
      hsts:
        enabled: true
        max-age: 31536000
        include-subdomains: true
      frame-options: SAMEORIGIN
      content-type-options: nosniff
      referrer-policy: no-referrer
      xss-protection: "0"
    propagation:
      enabled: true
      include:
        - X-Correlation-Id
        - X-Request-ID
        - X-User-Id
  audit:
    enabled: true
    web:
      enabled: true
      include-headers: true
      track-bodies: true
    aop:
      enabled: true
    dispatcher:
      async: true
    retention:
      enabled: true
      days: 90
    masking:
      enabled: true
      fields-by-key:
        - password
        - secret
        - token
        - ssn
    sinks:
      kafka:
        enabled: true
        topic: audit_logs
      otlp:
        enabled: false
      outbox:
        enabled: false
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
    timeout: ${REDIS_TIMEOUT:2s}
    key-prefix: ${REDIS_KEY_PREFIX:ejada}
    default-ttl: ${REDIS_DEFAULT_TTL:600s}
    reactive: false
  security:
    mode: hs256
    jwt:
      secret: ${JWT_SECRET:}
      token-period: ${JWT_TOKEN_PERIOD:15m}
    hs256:
      secret: ${JWT_SECRET:}
    resource-server:
      enabled: true
      disable-csrf: false
    stateless: true
    roles-claim: roles
    tenant-claim: tenant
