spring:
  config:
    import:
      - optional:classpath:/application-shared-dev.yaml
  redis:
   host: localhost
   port: 6379
  kafka:
   bootstrap-servers: localhost:9092
  flyway:
   enabled: true
   locations: classpath:db/migration/common,classpath:db/migration/{vendor}
  data:
   redis:
    repositories:
     enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/lms?currentSchema=setup
    username: postgres
    password: postgres
server:
  servlet:
    context-path: /core



