spring:
  config:
    import:
      - optional:classpath:/application-shared-common.yaml
      - optional:classpath:/application-shared-dev.yaml
  datasource:
    url: jdbc:postgresql://localhost:5432/lms?currentSchema=catalog
    username: postgres
    password: postgres
  flyway:
    default-schema: catalog
    schemas: catalog
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}

server:
  servlet:
    context-path: /core
