spring:
  application:
    name: lms-setup
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/tenant
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  redis:
    host: ${REDIS_HOST:redis}
    port: 6379
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /core
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/plain
      - text/css
      - application/json
      - application/javascript
    min-response-size: 2KB
  error:
    include-message: always
    include-binding-errors: always

shared:
  observability:
    application-name: lms-setup
  security:
    enable-role-check: true
    jwt:
      token-period: 15m
