apiVersion: apps/v1
kind: Deployment
metadata:
  name: ejada-tenant
  labels:
    app: ejada-tenant
    app.kubernetes.io/name: tenant-service
    app.kubernetes.io/instance: ejada-tenant
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: ejada-lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ejada-tenant
      app.kubernetes.io/name: tenant-service
  template:
    metadata:
      labels:
        app: ejada-tenant
        app.kubernetes.io/name: tenant-service
        app.kubernetes.io/instance: ejada-tenant
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: ejada-lms
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: /tenant/actuator/prometheus
    spec:
      containers:
        - name: app
          image: your.registry/ejada-tenant:1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres:5432/ejada?currentSchema=tenant
            - name: SPRING_DATASOURCE_USERNAME
              value: ejada
            - name: SPRING_DATASOURCE_PASSWORD
              value: ejada
            - name: SPRING_DATA_REDIS_HOST
              value: redis
            - name: SPRING_DATA_REDIS_PORT
              value: "6379"
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /tenant/actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /tenant/actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
