spring:
  config:
    import: optional:classpath:application-shared-platform-dev.yaml

app:
  schema: subscription
  cache-prefix: subscription
  kafka:
    client-id: ejada-subscription-dev
  subscription-approval:
    topic: tenant.subscription-approvals
    approval-role: ejada-officer
    consumer-group: tenant-approval-provisioner
  tenant-provisioning:
    topic: tenant.provisioning
    consumer-group: tenant-provisioning-publisher

shared:
  openapi:
    enabled: true
    title: " subscription Service API"
    description: "subscription service endpoints for subscription/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: subscription
      packages-to-scan:
        - com.ejada.subscription
    jwt-security: false
  security:
    subscription-claim: subscription
    enable-role-check: false
