groups:
  - name: gateway-observability
    rules:
      - alert: GatewayHighErrorRate
        expr: sum(rate(gateway_requests_by_tenant_total{statusCode=~"5.."}[5m]))
          /
          sum(rate(gateway_requests_by_tenant_total[5m])) > 0.05
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Gateway error rate above 5%"
          description: "5xx responses exceeded 5% of total gateway traffic over the last 5 minutes."

      - alert: GatewayRateLimitRejectionSpike
        expr: sum(rate(gateway_ratelimit_rejections_total[1m])) > 100
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Rate limit rejections spiking"
          description: "Gateway is rejecting more than 100 requests per minute due to rate limiting."

      - alert: GatewayCircuitBreakerOpen
        expr: max_over_time(gateway_circuit_breaker_state{state="open"}[30s]) > 0
        for: 30s
        labels:
          severity: critical
        annotations:
          summary: "Circuit breaker open"
          description: "One or more circuit breakers have remained open for over 30 seconds."

      - alert: GatewaySubscriptionValidationFailures
        expr: sum(rate(gateway_subscription_validation_outcomes_total{outcome="failure"}[5m]))
          /
          sum(rate(gateway_subscription_validation_outcomes_total[5m])) > 0.10
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Subscription validation failures >10%"
          description: "Subscription validation failures exceeded 10% of total validations over the last 5 minutes."
