spring:
  config:
    import: optional:classpath:application-shared-platform-dev.yaml
  datasource:
    url: "${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lms}?currentSchema=billing}"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-ejada
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000        # 30s
      connection-timeout: 300000 # 300s
      max-lifetime: 1800000      # 30m

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: billing
        hbm2ddl.create_namespaces: true
        format_sql: true
        jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}

  kafka:
    client-id: ejada-billing-dev

  data:
    redis:
      repositories:
        enabled: false

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,beans,conditions,configprops,loggers,threaddump
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    display-request-duration: true
    filter: true
    operationsSorter: method
    tagsSorter: alpha

shared:
  core:
    correlation:
      header-name: X-Correlation-Id
      generate-if-missing: true
      echo-response-header: true
    billing:
      enabled: true
      header-name: x_billing_id
      query-param: billingId
      default-policy: OPTIONAL
      echo-response-header: true
    cors:
      enabled: true
      allowed-origins: http://localhost:3000
      allowed-methods: GET,POST,PUT,DELETE,OPTIONS
      allowed-headers: "*"
  headers:
    enabled: true
    correlation:
      header: X-Correlation-Id
      auto-generate: true
      mandatory: true
    request:
      header: X-Request-ID
      auto-generate: true
      mandatory: true
    billing:
      header: x_billing_id
      auto-generate: false
      mandatory: false
    user:
      header: X-User-Id
      auto-generate: false
      mandatory: false
    mdc:
      enabled: true
    security:
      enabled: true
      hsts:
        enabled: true
        max-age: 31536000
        include-subdomains: true
      frame-options: SAMEORIGIN
      content-type-options: nosniff
      referrer-policy: no-referrer
      xss-protection: "0"
    propagation:
      enabled: true
      include:
        - X-Correlation-Id
        - X-Request-ID
        - x_billing_id
        - X-User-Id
  audit:
    enabled: true
    web:
      enabled: true
      include-headers: true
      track-bodies: true
    aop:
      enabled: true
    dispatcher:
      async: true
    retention:
      enabled: true
      days: 90
    masking:
      enabled: true
      fields-by-key:
        - password
        - secret
        - token
        - ssn
    sinks:
      db:
        enabled: true
        schema: billing
        table: audit_logs
      kafka:
        enabled: true
        topic: audit_logs
      otlp:
        enabled: false
      outbox:
        enabled: true
  openapi:
    enabled: true
    title: " billing Service API"
    description: "billing service endpoints for billing/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: billing
      packages-to-scan:
        - com.ejada.billing
    jwt-security: false
  redis:
    host: redis
    port: 6379
    timeout: 2s
    key-prefix: billing
    default-ttl: 600s
    reactive: false
  crypto:
    algorithm: AES_GCM
    in-memory:
      activeKid: ${CRYPTO_ACTIVE_KID:local-dev-key}
      keys:
        local-dev-key: ${CRYPTO_LOCAL_DEV_KEY:4J8bfqUaEqzJCQakoJPM3w==}
  security:
    mode: hs256
    jwt:
      secret: ${JWT_SECRET:7h1aH9UllV2E7Yka4P6s2F+1Vn6V5w9zIXhmJ5aB1kA=}
      token-period: 15m
    hs256:
      secret: ${JWT_SECRET:7h1aH9UllV2E7Yka4P6s2F+1Vn6V5w9zIXhmJ5aB1kA=}
    resource-server:
      enabled: true
      permit-all:
        - "/actuator/health"
      disable-csrf: false
    stateless: true
    roles-claim: roles
    billing-claim: billing
    enable-role-check: false

logging:
  level:
    root: ERROR
    com.ejada: ERROR
    com.ejada.audit.starter: ERROR
    com.ejada.audit.starter.core.dispatch: ERROR
    com.ejada.audit.starter.core.dispatch.sinks: ERROR
    org.hibernate.tool.schema: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.orm.jdbc.bind: ERROR
    org.springframework.cache: ERROR
    org.springframework.cache.interceptor.CacheAspectSupport: ERROR

debug: true
