spring:
  config:
    import: optional:classpath:application-shared-platform-dev.yaml

shared:
  openapi:
    enabled: true
    title: " billing Service API"
    description: "billing service endpoints for billing/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: billing
      packages-to-scan:
        - com.ejada.billing
    jwt-security: false
  security:
    billing-claim: billing
    enable-role-check: false

app:
  kafka:
    client-id: ejada-billing-dev
  billing:
    approval:
      topic: tenant.subscription-approvals
      consumer-group: billing-approval-listener
    provisioning:
      topic: billing.provisioning
      consumer-group: billing-provisioning-listener
    consumption:
      topic: billing.consumption
      consumer-group: billing-consumption-listener
