spring:
  config:
    import: optional:classpath:application-shared-tenant-qa.yaml

app:
  service-code: billing

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,beans,conditions,configprops,loggers,threaddump
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    display-request-duration: true
    filter: true
    operationsSorter: method
    tagsSorter: alpha

shared:
  core:
    billing:
      enabled: true
      header-name: x_billing_id
      query-param: billingId
      default-policy: OPTIONAL
      echo-response-header: true
  headers:
    billing:
      header: x_billing_id
      auto-generate: false
      mandatory: false
    propagation:
      enabled: true
      include:
        - X-Correlation-Id
        - X-Request-ID
        - x_billing_id
        - X-User-Id
  security:
    billing-claim: billing
  openapi:
    enabled: true
    title: "Ejada - billing Service API"
    description: "billing service endpoints for billing/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: billing
      packages-to-scan:
        - com.ejada.billing

    jwt-security: true

logging:
  level:
    root: ERROR                
    com.ejada: ERROR
    org.hibernate.SQL: ERROR   
    org.hibernate.orm.jdbc.bind: ERROR
    org.springframework.cache: ERROR
    org.springframework.cache.interceptor.CacheAspectSupport: ERROR

debug: false
