spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lms?currentSchema=entity
    username: postgres
    password: postgres

  redis:
    host: localhost
    port: 6379

  kafka:
    bootstrap-servers: 127.0.0.1:9092

  flyway:
    enabled: true
    default-schema: entity
    create-schemas: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations:
      - classpath:db/migration/common
      - classpath:db/migration/{vendor}
