apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-sentinel.fullname" . }}
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "redis-sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      port: {{ .Values.service.port }}
      targetPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-sentinel.fullname" . }}-headless
  labels:
    {{- include "redis-sentinel.labels" . | nindent 4 }}
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: {{ include "redis-sentinel.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: redis
      port: 6379
    - name: sentinel
      port: {{ .Values.sentinel.port }}
