spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/entitlements
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092

shared:
  security:
    resource-server:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080
