spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379

app:
  analytics:
    refresh-cron: "0 */15 * * * *" # refresh every 15 minutes

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      probes:
        enabled: true

shared:
  security:
    resource-server:
      enabled: false
    jwt:
      secret: ${JWT_SECRET:7h1aH9UllV2E7Yka4P6s2F+1Vn6V5w9zIXhmJ5aB1kA=}
      token-period: 15m
