spring:
  application:
    name: analytics-service
  main:
    lazy-initialization: ${SPRING_MAIN_LAZY_INITIALIZATION:true}
  lifecycle:
    timeout-per-shutdown-phase: 20s
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lms}?currentSchema=${app.schema}}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: ${app.schema}
        hbm2ddl:
          create_namespaces: true
        format_sql: true
        jdbc:
          time_zone: UTC
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
    schemas: ${app.schema}
    default-schema: ${app.schema}
  sql:
    init:
      mode: never
  cache:
    type: redis
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:redis}
      port: ${SPRING_DATA_REDIS_PORT:6379}

app:
  schema: tenant_usage
  cache-prefix: analytics
  analytics:
    refresh-cron: "0 */15 * * * *" # refresh every 15 minutes

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include:
          - health
          - info
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true
  metrics:
    export:
      simple:
        enabled: false
      prometheus:
        enabled: false

  health:
    redis:
      enabled: ${shared.redis.enabled:true}

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false

shared:
  redis:
    enabled: ${SHARED_REDIS_ENABLED:true}
  security:
    mode: ${SHARED_SECURITY_MODE:hs256}
    hs256:
      secret: ${SHARED_SECURITY_HS256_SECRET:7h1aH9UllV2E7Yka4P6s2F+1Vn6V5w9zIXhmJ5aB1kA=}
    resource-server:
      enabled: true
      verify-tenant-claim: true
    tenant-verification:
      strict-mode: true
      require-tenant-header: true
    jwt:
      secret: ${JWT_SECRET:7h1aH9UllV2E7Yka4P6s2F+1Vn6V5w9zIXhmJ5aB1kA=}
      token-period: 15m

logging:
  level:
    root: INFO
    org.springframework: INFO
