spring:
  config:
    import: optional:classpath:application-shared-tenant-qa.yaml

app:
  service-code: tenant
  schema: tenant
  subscription-approval:
    topic: tenant.subscription-approvals
    approval-role: ejada-officer
    consumer-group: tenant-approval-listener

management:
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: health,info,metrics,prometheus,beans,conditions,configprops,loggers,threaddump
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    display-request-duration: true
    filter: true
    operationsSorter: method
    tagsSorter: alpha

shared:
  openapi:
    enabled: true
    title: "Ejada - tenant Service API"
    description: "tenant service endpoints for tenant/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: tenant
      packages-to-scan:
        - com.ejada.tenant
    jwt-security: true

logging:
  level:
    root: ERROR                
    com.ejada: ERROR
    org.hibernate.SQL: ERROR   
    org.hibernate.orm.jdbc.bind: ERROR
    org.springframework.cache: ERROR
    org.springframework.cache.interceptor.CacheAspectSupport: ERROR

debug: false

