spring:
  config:
    import: optional:classpath:application-shared-platform-dev.yaml
  datasource:
    url: "${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:lms}?currentSchema=tenant}"
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-ejada
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000        # 30s
      connection-timeout: 300000 # 300s
      max-lifetime: 1800000      # 30m

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: tenant
        hbm2ddl.create_namespaces: true
        format_sql: true
        jdbc.time_zone: UTC

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
    schemas: public,tenant
    default-schema: tenant

  kafka:
    client-id: ejada-tenant-dev
shared:
  openapi:
    enabled: true
    title: " tenant Service API"
    description: "tenant service endpoints for tenant/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: tenant
      packages-to-scan:
        - com.ejada.tenant
    jwt-security: false

app:
  schema: tenant
  cache-prefix: tenant
  subscription-approval:
    topic: tenant.subscription-approvals
    approval-role: ejada-officer
    consumer-group: tenant-approval-listener
