spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/lms
    username: ${POSTGRES_USER:app_user}
    password: ${POSTGRES_PASSWORD:postgres}
  flyway:
    locations: classpath:db/migration,classpath:db/migration/{vendor}
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 8080
