spring:
  config:
    import:
      - classpath:application-shared-api-gateway.yaml
  datasource:
    url: "${DB_URL:jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:ejada}?currentSchema=tenant}"
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: HikariPool-Ejada
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000        # 30s
      connection-timeout: 300000 # 300s
      max-lifetime: 1800000      # 30m
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: tenant
        hbm2ddl.create_namespaces: true
        format_sql: true
        jdbc.time_zone: UTC
  flyway:
    enabled: false
    baseline-on-migrate: true
  kafka:
    client-id: ejada-tenant-qa
    consumer:
      group-id: ejada-backend-qa

shared:
  core:
    tenant:
      enabled: true
      header-name: x_tenant_id
      query-param: tenantId
      default-policy: OPTIONAL
      echo-response-header: true
  headers:
    tenant:
      header: x_tenant_id
      auto-generate: false
      mandatory: false
    security:
      xss-protection: "1; mode=block"
    propagation:
      include:
        - X-Correlation-Id
        - X-Request-ID
        - x_tenant_id
        - X-User-Id
  audit:
    sinks:
      db:
        schema: tenant
  openapi:
    enabled: true
    title: "Ejada - tenant Service API"
    description: "tenant service endpoints for tenant/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: tenant
      packages-to-scan:
        - com.ejada.tenant
    jwt-security: true
  redis:
    key-prefix: ejada
  crypto:
    algorithm: AES_GCM
    in-memory:
      activeKid: ${CRYPTO_ACTIVE_KID:local-qa-key}
      keys:
        local-qa-key: ${CRYPTO_LOCAL_QA_KEY}
  security:
    jwt:
      secret: ${JWT_SECRET}
    hs256:
      secret: ${JWT_SECRET}
    resource-server:
      permit-all: ["**"]
    enable-role-check: true

logging:
  level:
    root: ERROR
    com.ejada: ERROR
    org.hibernate.SQL: ERROR
    org.hibernate.orm.jdbc.bind: ERROR
    org.springframework.cache: ERROR
    org.springframework.cache.interceptor.CacheAspectSupport: ERROR

debug: false
