spring:
  config:
    import: optional:classpath:application-shared-platform-dev.yaml

shared:
  openapi:
    enabled: true
    title: " tenant Service API"
    description: "tenant service endpoints for tenant/platform configuration."
    version: "1.0.0"
    servers:
      - http://localhost:8080/core
    group:
      name: tenant
      packages-to-scan:
        - com.ejada.tenant
    jwt-security: false

app:
  schema: tenant
  cache-prefix: tenant
  kafka:
    client-id: ejada-tenant-dev
  subscription-approval:
    topic: tenant.subscription-approvals
    approval-role: ejada-officer
    consumer-group: tenant-approval-listener
