spring:
  application:
    name: tenant-service
  profiles:
    active: dev
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/lms
    username: postgres
    password: postgres
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public,tenant
    default-schema: tenant
    url: jdbc:postgresql://postgres:5432/lms
    user: postgres
    password: postgres
  webflux:
    base-path: /tenant
server:
  port: 8080
  shutdown: graceful
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/plain
      - text/css
      - application/json
      - application/javascript
    min-response-size: 2KB
  error:
    include-message: always
    include-binding-errors: always

shared:
  observability:
    application-name: tenant-service
  security:
    enable-role-check: true
    jwt:
      token-period: 15m