spring:
  application:
    name: tenant-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    schemas: public,tenant
    default-schema: tenant
server:
  port: 8080
  shutdown: graceful
  servlet:
    context-path: /tenant
  compression:
    enabled: true
    mime-types:
      - text/html
      - text/plain
      - text/css
      - application/json
      - application/javascript
    min-response-size: 2KB
  error:
    include-message: always
    include-binding-errors: always

shared:
  observability:
    application-name: tenant-service
  security:
    enable-role-check: true
    jwt:
      token-period: 15m
