spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lms?currentSchema=tenant_core
    username: app_user
    password: postgres
  redis:
    host: 127.0.0.1
    port: 6379
  kafka:
    bootstrap-servers: 127.0.0.1:9092
  flyway:
    enabled: true
    default-schema: tenant_core
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
server:
  port: 8080
shared:
  openapi:
    title: Tenant API
    description: Admin gateway APIs
