spring:
  profiles:
    active: dev
  flyway:
    enabled: true
    default-schema: tenant_core
    baseline-on-migrate: true
    validate-on-migrate: true
    clean-disabled: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
server:
  port: 8080
