spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:postgresql://localhost:5432/lms?currentSchema=tenant_core
    username: postgres
    password: postgres
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    enabled: true
    default-schema: tenant_core
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
server:
  port: 8080
shared:
  openapi:
    title: Tenant API
    description: Admin gateway APIs
