spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms
    username: app_user
    password: postgres
  redis:
    host: localhost
    port: 6379
  kafka:
    bootstrap-servers: localhost:9092
  flyway:
    enabled: true
    locations: classpath:db/migration/common,classpath:db/migration/{vendor}
server:
  port: 8080
