spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

shared:
  redis:
    enabled: ${SHARED_REDIS_ENABLED:true}
    url: ${SHARED_REDIS_URL:${REDIS_URL:}}
    host: ${SHARED_REDIS_HOST:${REDIS_HOST:redis}}
    port: ${SHARED_REDIS_PORT:${REDIS_PORT:6379}}
    password: ${SHARED_REDIS_PASSWORD:${REDIS_PASSWORD:}}
    timeout: ${SHARED_REDIS_TIMEOUT:5s}
    key-prefix: ${SHARED_REDIS_KEY_PREFIX:shared}
    default-ttl: ${SHARED_REDIS_DEFAULT_TTL:10m}
