spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:postgres}:5432/lms
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
server:
  port: 8080
