spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/lms?currentSchema=tenant_policy
    username: postgres
    password: postgres
  flyway:
    enabled: true
    default-schema: tenant_policy
    schemas: tenant_policy
server:
  port: 8080
shared:
  core:
    correlation:
      header-name: X-Correlation-Id
      generate-if-missing: true
      echo-response-header: true
    tenant:
      enabled: true
      header-name: x_tenant_id
      query-param: tenantId
      default-policy: OPTIONAL
      echo-response-header: true
