spring:
  application:
    name: sec-service
  datasource:
    url: jdbc:postgresql://localhost:5432/secdb
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    locations: classpath:db/migration

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when_authorized

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

security:
  # lifetime of refresh tokens in seconds (default 30 days)
  refresh-token-ttl: 2592000
  # lifetime of password reset tokens in seconds (default 24 hours)
  reset-token-ttl: 86400

logging:
  level:
    root: INFO