name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B clean verify --file pom.xml

      # Optional: Upload test results
      # - name: Publish Test Report
      #   if: always()
      #   uses: scacap/action-surefire-report@v1
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     report_paths: '**/surefire-reports/TEST-*.xml'
