spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

shared:
  security:
    mode: ${SHARED_SECURITY_MODE:hs256}
    hs256:
      secret: ${SHARED_SECURITY_HS256_SECRET:change-me}
    resource-server:
      enabled: ${SHARED_SECURITY_RESOURCE_SERVER_ENABLED:true}
      verify-tenant-claim: ${SHARED_SECURITY_RESOURCE_SERVER_VERIFY_TENANT_CLAIM:false}
    tenant-verification:
      strict-mode: ${SHARED_SECURITY_TENANT_VERIFICATION_STRICT_MODE:false}
      require-tenant-header: ${SHARED_SECURITY_TENANT_VERIFICATION_REQUIRE_TENANT_HEADER:false}
    roles-claim: ${SHARED_SECURITY_ROLES_CLAIM:roles}
    scope-claim: ${SHARED_SECURITY_SCOPE_CLAIM:scope}
